### ISSUE TITLE
1.6.2 Wireless Connector Issue

### ISSUE THREAD

**Issue by Hexxonite** [NillerMedDild/Enigmatica2Expert#1163]
**Modpack version**
1.6.2

**Can the issue be reproduced?**
unknown

**Logs**

`[15:06:38] [Server thread/WARN] [ae2stuff]: Failed setting up wireless link BlockPos{x=-797, y=81, z=-563} <-> BlockPos{x=-763, y=92, z=-562}
appeng.api.exceptions.SecurityConnectionException: Connection failed due to different security realms.
        at appeng.me.GridConnection.create(GridConnection.java:258) ~[GridConnection.class:?]
        at appeng.core.api.ApiGrid.createGridConnection(ApiGrid.java:62) ~[ApiGrid.class:?]
        at net.bdew.ae2stuff.machines.wireless.TileWireless$$anonfun$setupConnection$1.apply(TileWireless.scala:63) [TileWireless$$anonfun$setupConnection$1.class:?]
        at net.bdew.ae2stuff.machines.wireless.TileWireless$$anonfun$setupConnection$1.apply(TileWireless.scala:61) [TileWireless$$anonfun$setupConnection$1.class:?]
        at scala.Option.foreach(Option.scala:245) [scala-library-2.11.1.jar:?]
        at net.bdew.ae2stuff.machines.wireless.TileWireless.setupConnection(TileWireless.scala:61) [TileWireless.class:?]
        at net.bdew.ae2stuff.machines.wireless.TileWireless$$anonfun$1.apply$mcV$sp(TileWireless.scala:40) [TileWireless$$anonfun$1.class:?]
        at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) [Event0$$anonfun$trigger$1.class:?]
        at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) [Event0$$anonfun$trigger$1.class:?]
        at scala.collection.immutable.List.foreach(List.scala:383) [scala-library-2.11.1.jar:?]
        at net.bdew.lib.Event0.trigger(Event.scala:19) [Event0.class:?]
        at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24) [TileTicking$class.class:?]
        at net.bdew.ae2stuff.machines.wireless.TileWireless.func_73660_a(TileWireless.scala:26) [TileWireless.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
`

**Issue**
When using the Wireless Connectors of AE2 on my ME System, it works fine with two Connector Pairs (4 overall) but when I connect the 3rd pair, the ME shuts down and the above message is produced on the server.
I am not sure what these "security reralms" should reffer to since one of the two pairs is already working in the chunk where I wanted to place the 3rd pair.

The ME system has definetley enough power to use the 3rd pair but I can't get it to work, even tried switching the place where I put it.

I am at a loss rn and would appreciate any help, thanks in advance!

**Comment by NillerMedDild** [comment]
Have you tried breaking your Security Station?

**Comment by Hexxonite** [comment]
Just did it, with the same result \:

**Comment by NillerMedDild** [comment]
Alright, I'll look into it.

**Comment by Hexxonite** [comment]
I can confirm this bug to be present in 1.5.8 already, and probably being caused by Ae2Stuff lib.. maybe updaing these would solve the problem. Ill look if the bug was already found and fixed there and report back or open a pull request.

**Comment by Hexxonite** [comment]
It seems this issue is caused by the ME system's energy buffer which is about 3k AE/RF.
If the energy cost of the connected Wireless Connectors exceeds this limit, the ME shuts down since it cant supply the devices with enough energy.

A workaround is to place the connectors closer to each other to not exceed the energy limit.
If they arent placed verry far from each other, even a small amount of distance can make a significant difference in energy cost. 

I would like if you could power the Wireless Connectors independent of the ME System so you dont run into this bottleneck. Otherwise there might be a way to extend the ME buffer with energy cells, havent tried that yet though.

**Comment by MaxNeedsSnacks** [comment]
Here's a little hint if you wanna make further-range wireless connections: Add Energy Cells to your AE network, they significantly increase the energy buffer and the limit at which your network is able to transmit power. It's still weird that this is giving a "security realm" error, but that's probably just because your security station went down with the rest of the network.

I'm gonna mark this as "Invalid", but if I was incorrect about that decision, feel free to ping me again ^^

**Comment by Hexxonite** [comment]
alright, thanks :)
