### ISSUE TITLE
Cannot autocraft through WCT

### ISSUE THREAD

**Issue by randomlypickedname** [NillerMedDild/Enigmatica2Expert#140]
#### Issue Description
I'm unable to autocraft through a WCT. I've tried spawning a new one and linking it, I've tried breaking my controllers and replacing them, and I've tried through other AE2 terminals, and only the AE2 terminals work.

#### Modpack version (Do not use "latest")
1.31

https://imgur.com/a/EvZ8o2G

**Comment by codeka** [comment]
Looks like some sort of version incompatibility between WCT and AE2.

AE2 made [this change](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3434), but WCT is [still relying on](https://github.com/p455w0rd/WirelessCraftingTerminal/blob/master/src/main/java/p455w0rd/wct/container/CraftingCPURecord.java) the old methods existing:

Caused by: java.lang.NoSuchMethodError: appeng.util.ItemSorters.compareLong(JJ)I
	at p455w0rd.wct.container.CraftingCPURecord.compareTo(CraftingCPURecord.java:39) ~[CraftingCPURecord.class:?]
	at p455w0rd.wct.container.CraftingCPURecord.compareTo(CraftingCPURecord.java:23) ~[CraftingCPURecord.class:?]
	at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source) ~[?:1.8.0_171]
	at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.8.0_171]

**Comment by codeka** [comment]
Reverting AE2 to rv5.stable fixed this for me. Someone on the discord pointed to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3578 where the AE2 devs say "rv6 is still alpha and not considered usable for production. If "All the Mods 3" decides to test it, it is recommended to remove all AE2 addons until AE2 reaches stable or at least some time into the beta phase."

**Comment by NillerMedDild** [comment]
Reverted to the prior version of AE2.
