### ISSUE TITLE
Crash when exiting a single player world

### ISSUE THREAD

**Issue by bloop428** [NillerMedDild/Enigmatica2Expert#173]
#### Issue Description
The game crashes when exiting to the title screen in single player. Possibly caused by opening to LAN.

#### Modpack version (Do not use "latest")
1.33

#### Crash Report

https://gist.github.com/bloop428/4717461a49ba5c5dbaec81966f7bbe4f (No crash report is created. this is the best i can give)

**Comment by bloop428** [comment]
That is the latest.log file...

**Comment by NillerMedDild** [comment]
The entirety of it? It doesn't even show the game starting.

**Comment by Discomanco** [comment]
The latest.log tells nothing. The last things it says is: Player logged out, stopping servers and services. Nothing more

**Comment by bloop428** [comment]
Never happens when not opening to LAN from what I've experienced. If you scroll up a small bit from the very bottom of the file, there is some errors I think.

**Comment by Discomanco** [comment]
```
[20:56:26] [Netty Local Client IO #1/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[20:56:26] [Netty Local Client IO #1/INFO]: [AstralSorcery] Cleaning client cache...
[20:56:26] [Netty Local Client IO #1/INFO]: [AstralSorcery] Cleared cached client data! Disconnected from server.
[20:56:26] [Netty Local Client IO #1/INFO]: Building block state lookup table...
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/WARN]: Some mod returns null from Block.getPickBlock, should return ItemStack.EMPTY at this point. Block in question: Block{architecturecraft:shape}
[20:56:26] [Netty Local Client IO #1/INFO]: Built    block state lookup table in 589 ms.
[20:56:26] [Netty Local Client IO #1/INFO]: Scheduling client settings reset.
[20:56:26] [main/INFO]: Mapping halted in C:\Users\Bloop\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\journeymap\data\sp\New World\DIM0
[20:56:26] [Server thread/INFO]: _Bloop lost connection: Disconnected
[20:56:26] [Server thread/INFO]: _Bloop left the game
[20:56:26] [Server thread/WARN]: Mod was keeping bauble items in reserve for player %s but they logged out! Items are being dropped.
[20:56:26] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:56:26] [Server thread/INFO]: [lain.mods.cos.InventoryManager:onServerStopping:234]: Server is stopping... force saving all loaded CosmeticArmor data.
[20:56:26] [Server thread/INFO]: [lain.mods.cos.InventoryManager:onServerStopping:237]: c2f80809-4327-475b-82bf-e92eb3d5d434
[20:56:26] [Server thread/INFO]: Stopping server
[20:56:26] [Server thread/INFO]: Saving players
[20:56:26] [Server thread/INFO]: Saving worlds
[20:56:26] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[20:56:27] [Server thread/INFO]: Saving chunks for level 'New World'/Spectre
[20:56:27] [Server thread/INFO]: Saving chunks for level 'New World'/Storage Cell
[20:56:27] [Server thread/INFO]: Removing aura cache for world 0
[20:56:27] [Server thread/INFO]: Removing aura cache for world -343800852
[20:56:27] [Server thread/INFO]: Removing aura cache for world 2
[20:56:27] [Server thread/INFO]: Unloading dimension 0
[20:56:27] [Server thread/INFO]: Unloading dimension -343800852
[20:56:27] [Server thread/INFO]: Unloading dimension 2
[20:56:28] [Thread-49/INFO]: Stopping aura thread for dim 0
[20:56:28] [Thread-59/WARN]: No auras found!
[20:56:28] [Thread-61/WARN]: No auras found!
[20:56:28] [Thread-59/INFO]: Stopping aura thread for dim -343800852
[20:56:28] [Thread-61/INFO]: Stopping aura thread for dim 2
[20:56:32] [Server thread/ERROR]: Invalid BasicBlock. type: 0, meta: 32767
[20:56:32] [Server thread/ERROR]: Invalid BasicBlock. type: 1, meta: 32767
[20:56:33] [Server thread/INFO]: JEI search tree manager injection complete!
[20:56:35] [Server thread/INFO]: Applying holder lookups
[20:56:35] [Server thread/INFO]: Holder lookups applied
[20:56:35] [Server thread/INFO]: Unloaded WorldData!
[20:56:35] [Server thread/INFO]: Cleaning up all world data: 2 data blobs
[20:56:35] [Server thread/INFO]: RFTools Dimensions: server is stopping. Shutting down gracefully
[20:56:35] [Server thread/INFO]: Cleaning up RFTools dimensions
```
That's all the log says from when you stop the local server (aka SP world). It throws some warnings at ArchitechtureCraft, but no errors or fatals

**Comment by bloop428** [comment]
`[19:30:12] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:30:12] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:30:12] [Server thread/INFO]: Unloading dimension 1
[19:30:12] [Server thread/INFO]: Removing aura cache for world -1
[19:30:12] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:30:12] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:30:12] [Server thread/INFO]: Unloading dimension -1
[19:30:12] [Server thread/INFO]: Removing aura cache for world 144
[19:30:12] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:30:12] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:30:12] [Server thread/INFO]: Unloading dimension 144
[19:30:12] [Server thread/INFO]: Removing aura cache for world -11325
[19:30:12] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:30:12] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:30:12] [Server thread/INFO]: Unloading dimension -11325
[19:30:12] [Server thread/INFO]: Removing aura cache for world -2
[19:30:12] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:30:12] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:30:12] [Server thread/INFO]: Unloading dimension -2
[19:30:12] [Server thread/INFO]: Removing aura cache for world 7
[19:30:12] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:30:12] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2888_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]`

**Comment by NillerMedDild** [comment]
That's perfectly normal, it's very unlikely that that is the cause.

**Comment by NillerMedDild** [comment]
Edit: After searching through the JourneyMap github, it looks like it is the source of the crash. They're aware of the issue, but do not have time to fix it.
