### ISSUE TITLE
Crash with SP worlds

### ISSUE THREAD

**Issue by Zenthae** [NillerMedDild/Enigmatica2Expert#1840]
**Modpack version**
1.81a

**Issue**
The game crash when trying to join a Singleplayer world after play on Multiplayer

**Logs**
```log
java.lang.NullPointerException: Exception in server tick loop
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.<init>(GenericChunkGenerator.java:215)
	at mcjty.rftoolsdim.dimensions.world.GenericWorldProvider.func_186060_c(GenericWorldProvider.java:356)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:848)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:118)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NillerMedDild** [comment]
Thanks for the report. May I have your complete latest.log please?
