### ISSUE TITLE
Bibliocraft crashing players

### ISSUE THREAD

**Issue by samuellapointe** [NillerMedDild/Enigmatica2Expert#1891]
**Modpack version**
1.82a

**Issue**
Players randomly crash to desktop while playing, server log shows bibliocraft error. Our base currently has bibliocraft labels on chests, but it's the only item from this mod that's present so far I think.

**Logs**
```
[22:35:23] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityLabel.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_241]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_241]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityLabel.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at jds.bibliocraft.tileentities.TileEntityLabel.getStackInSlot(TileEntityLabel.java) ~[TileEntityLabel.class:?]
        at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:185) ~[Radar$PacketPing.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_241]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by NillerMedDild** [comment]
Thanks for the report - I'm afraid BiblioCraft is unmaintained so this will not be fixed. Your best bet is to remove any complex block from the labels, or remove the Labels entirely. 

This crash *may* also be avoided by ensuring you're all using a new Java 8 version, as anything else seems fairly crash prone.
