### ISSUE TITLE
Better Questing making enormous tick lag on server

### ISSUE THREAD

**Issue by wadabla48** [NillerMedDild/Enigmatica2Expert#452]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Better Questing Mod is making enormous tick lag on server using 25 000 microseconds/tick

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert v 1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**
Maybe reducing the update delay of the quest book might be a good fix option but I didn't find the option in the config file of the mod

**Comment by GoldenKeyboard** [comment]
If you can grab me the server log I can look into it.

**Comment by NillerMedDild** [comment]
Thank you for the report, the mod dev is aware of the issue and is trying to fix it. The lag scales up with number of online players. I suggest limiting how many players can be on your server at the same time, until the issue is resolved.

**Comment by wadabla48** [comment]
Here are the server log and debug files
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2711082/latest.log)
[debug.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2711083/debug.log)

**Comment by GoldenKeyboard** [comment]
> Here are the server log and debug files
> [latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2711082/latest.log)
> [debug.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2711083/debug.log)

Delete this post immediately, it has your ip in it

**Comment by wadabla48** [comment]
> > Here are the server log and debug files
> > [latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2711082/latest.log)
> > [debug.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2711083/debug.log)
> 
> Delete this post immediately, it has your ip in it

**Comment by GoldenKeyboard** [comment]
The post not the issue

**Comment by wadabla48** [comment]
Now delete your lol

**Comment by GoldenKeyboard** [comment]
I have the files, I'll do some digging.
Just be more careful about scrubbing your ip from log files in the future.

**Comment by wadabla48** [comment]
Actually it's not mine but yeah sorry

**Comment by GoldenKeyboard** [comment]
```
[18:47:34] [pool-4-thread-1/ERROR] [betterquesting]: An error occured while loading JSON from file:
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 41632 column 8 path $.questProgress:9.680:10.tasks:9.0:10.userProgress:9.1:10.data:9
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[Gson.class:?]
	at betterquesting.api.utils.JsonHelper.lambda$ReadFromFile$0(JsonHelper.java:170) ~[JsonHelper.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.io.EOFException: End of input at line 41632 column 8 path $.questProgress:9.680:10.tasks:9.0:10.userProgress:9.1:10.data:9
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[TypeAdapters$35$1.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	... 6 more
```

That error is thrown multiple times throughout the log. See if fixing that file solves the issue.

**Comment by wadabla48** [comment]
We tried but actually it did nothing, the error is verry caused by the betterquesting mod

**Comment by GoldenKeyboard** [comment]
https://github.com/Funwayguy/BetterQuesting/pull/512

Seems that it is already resolved in experimental.
Here are the downloads for those files, please tell me if it resolves your issues.
https://minecraft.curseforge.com/projects/better-questing/files/2651557

**Comment by wadabla48** [comment]
Thanks we'll try that with the next update for the modpack thanks
