### ISSUE TITLE
Enigmatica2Exper  v.1.58 world not loading 

### ISSUE THREAD

**Issue by daniel180281** [NillerMedDild/Enigmatica2Expert#991]
**Modpack version**
Enigmatica2Exper  v.1.58

**Issue**
I cant get the world to load is stuck in loading world for over a hour  

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report. I need your `latest.log` file to troubleshoot the issue.

The `latest.log` file can be found in the `logs` folder of the Enigmatica modpack folder.

**Comment by Stians92** [comment]
I'm not sure if Daniel here is having the same issue as me, but I ran into this error today after updating from v.1.56 to v.1.58

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Corrupted loading model stack: appliedenergistics2:item/dummy_fluid_item_base != appliedenergistics2:item/facade_base
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper.bakeParallel(ModelLoaderParallelHelper.java:79)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:108)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Corrupted loading model stack: appliedenergistics2:item/dummy_fluid_item_base != appliedenergistics2:item/facade_base
	at appeng.client.render.FacadeItemModel.getBaseModel(FacadeItemModel.java:55)
	at appeng.client.render.FacadeItemModel.getDefaultState(FacadeItemModel.java:83)
	at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper.lambda$bakeParallel$0(ModelLoaderParallelHelper.java:83)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Corrupted loading model stack: appliedenergistics2:item/dummy_fluid_item_base != appliedenergistics2:item/facade_base
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:178)
	at appeng.client.render.FacadeItemModel.getBaseModel(FacadeItemModel.java:51)
	... 12 more
```

**Comment by MaxNeedsSnacks** [comment]
Closed due to lack of response from the original author.
